### ISSUE TITLE
Error with libindystrgpostgres when create credential definition 

### ISSUE THREAD

**Issue by anhem115** [bcgov/von-network#120]
I have another problem with the python file when trying to create the credential definition.

```
➜  von-network git:(master) ✗ ./manage \
  -v ${PWD}/cli-scripts/ \
  cli \
  walletName=myorg_issuer \
  storageType=default
  storageConfig={} storageCredentials={} walletKey=${key} \
  poolName=localpool \
  authorDid=NFP8kaWvCupbDQHQhErwXb \
  schemaId=${schemaID} \
  schemaName=anh-permit.anh-co \
  schemaVersion=1.0.0 \
  schemaAttributes=name \
  tag=tag \
  python cli-scripts/cred_def.py
Loading postgres
Traceback (most recent call last):
  File "cli-scripts/cred_def.py", line 145, in <module>
    stg_lib = CDLL("libindystrgpostgres.so")
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libindystrgpostgres.so, 6): image not found
```
I didn't use postgres in my case, so I let it default storateType here

**Comment by WadeBarnes** [comment]
Using the latest code, after `./manage build`, setting up the wallet, pool, etc.  I can run this, without that error;
```
./manage \
  -v ${PWD}/cli-scripts/ \
  cli \
  walletName=myorg_issuer \
  walletKey=${key} \
  poolName=localpool \
  authorDid=NFP8kaWvCupbDQHQhErwXb \
  schemaId=${schemaID} \
  schemaName=ian-permit.ian-co \
  schemaVersion=1.0.0 \
  schemaAttributes=corp_num,legal_name,permit_id,permit_type,permit_issued_date,permit_status,effective_date \
  tag=tag \
  python cli-scripts/cred_def.py
```

`ibindystrgpostgres.so` should be built into the image used to run the cli commands.

**Comment by anhtranEH** [comment]
I think the problem is that I didn't use setup the wallet and pool by ./manage command but I run the indy-cli directly

**Comment by WadeBarnes** [comment]
Does that mean this issue is resolved for you now?

**Comment by anhem115** [comment]
Yeah, I just need to run this command
```load-plugin library=libindystrgpostgres.so initializer=postgresstorage_init```
Everything is ok for now.
