### ISSUE TITLE
Building troubles

### ISSUE THREAD

**Issue by surfnet-niels** [bcgov/von-network#130]
Hi 
First of all, many thanks for providing this and its the elaborate documentation!
I am running into an issue however. I am fairly sure it is not directly related to the setup, but perhaps you could provide some guidance on resolving it.

I want to run a 'VPS' instance (https://github.com/bcgov/von-network#running-the-network-on-a-vps) of the von network on Ubuntu 18.04 LTS using docker ce 19.03.13.

When building using ./manage build I get the following error:

```ubuntu@von-network:~/von-network$ ./manage build
Unable to find image 'eclipse/che-ip:latest' locally
latest: Pulling from eclipse/che-ip
d6a5679aa3cf: Already exists
4498fa6d0d1b: Already exists
Digest: sha256:2ac584b1bd6e6ec2379760dd90ae63b61b67f40cc6331c6bfc46e5e747b767b5
Status: Downloaded newer image for eclipse/che-ip:latest
free(): invalid pointer
SIGABRT: abort
PC=0x7f12a7330f47 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420049cc0, 0xc420049ce8)
	/usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420049c90 sp=0xc420049c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x2101270)
	github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420049cc0 sp=0xc420049c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x2101270)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420049cf8 sp=0xc420049cc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc4200180c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420049da0 sp=0xc420049cf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420049e88, 0x410022, 0xc420060220)
	<autogenerated>:4 +0x46 fp=0xc420049de0 sp=0xc420049da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc420080008, 0x0, 0x10)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420049e68 sp=0xc420049de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffee9a0b66e, 0x4, 0x7560a0, 0xc420080000, 0x7560e0, 0xc420080008, 0x40e398, 0x4d35c0)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420049ed8 sp=0xc420049e68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420049f58 sp=0xc420049ed8
main.main()
	/build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420049f88 sp=0xc420049f58
runtime.main()
	/usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420049fe0 sp=0xc420049f88
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420049fe8 sp=0xc420049fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffee9a09a80
rcx    0x7f12a7330f47
rdx    0x0
rdi    0x2
rsi    0x7ffee9a09810
rbp    0x7ffee9a09b80
rsp    0x7ffee9a09810
r8     0x0
r9     0x7ffee9a09810
r10    0x8
r11    0x246
r12    0x7ffee9a09a80
r13    0x1000
r14    0x0
r15    0x30
rip    0x7f12a7330f47
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Sending build context to Docker daemon  316.4kB
Step 1/9 : FROM bcgovimages/von-image:node-1.12-3
...
```
Interestingly it does not seem to prevent the eclipse/che-ip image from being build, and I can run that independently using e.g. "docker run eclipse/che-ip". The other images build just fine.

If I then want to start the network using "./manage start --logs" 
I get a complaint from docker-compose:
```ubuntu@von-network:~/von-network$ ./manage start --logs
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
  docker-compose -h|--help
```

Clearly docker compose is unhappy with one of the docker-compose commands being build in the manage script, but given there are several, it is a bit hard to diagnose which one is failing :(
I am also unsure if this is related to the above issue with eclipse/che-ip

Any suggestions on how to resolve this?
Many thanks!

**Comment by WadeBarnes** [comment]
The 2 issues are unrelated.  To fix the docker-compose issue, update/upgrade your version of docker-compose.  For the `eclipse/che-ip` image download issue, try removing the existing `eclipse/che-ip` image from your system so a fresh copy gets downloaded.

**Comment by surfnet-niels** [comment]
Hello Wade,
Many thanks for your quick response! 
Based on your suggestion, I am happy to report an upgrade to Ubuntu 20.04 LTS resolved all of the above issues.
Nodes and webserver seem to be up and running.
