### ISSUE TITLE
"ModuleNotFoundError: No module named 'indy'" - where has 'ledger' and 'pool' moved to ?

### ISSUE THREAD

**Issue by shearichard** [bcgov/von-network#245]
I am following the instructions at https://github.com/bcgov/von-network#running-the-web-server-on-your-local-machine .

When I execute the following command I get the error "ModuleNotFoundError: No module named 'indy'" - can anyone tell me where the 'ledger' and 'pool' objects can now be found ?

```
(venv) rshea@tana:~/dev/von-network$ GENESIS_FILE=~/dev/aries-cloudagent-python-sandbox/genesis-file-downloaded-from-von.txt PORT=9000 python -m server.server
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rshea/dev/von-network/server/server.py", line 14, in <module>
    from .anchor import (
  File "/home/rshea/dev/von-network/server/anchor.py", line 17, in <module>
    from indy import ledger, pool
ModuleNotFoundError: No module named 'indy'
```

**Comment by WadeBarnes** [comment]
The recommended way to run `von-network` is using docker through the `./manage` script.  See; https://github.com/bcgov/von-network/blob/main/docs/UsingVONNetwork.md.

**Comment by darapich92** [comment]
Hello @WadeBarnes, I am sorry to ask you a question. I run `./manage indy-cli` for creating the wallet. My main purpose is to create the posgresql wallet. I also loaded the posgres plug-in but I received the message "Unknown wallet storage type". I tried many way to change the name `storage_type` but it was not succeeded. Do you know how solve this problem? thank you very much!

**Comment by jamshale** [comment]
@WadeBarnes  `./manage` works well but i'm trying to have my own local agents/controllers as well as the aries demo agents connect to my von-network and having quite a bit of issues because of the docker ip address in the genesis file. 
Do you have any resources or suggestions about?

I've found some documentation `https://github.com/hyperledger/indy-sdk/blob/main/README.md#how-to-start-local-nodes-pool-with-docker` but it seems out of date. Tried a lot of things but haven't got it to work. I'm on windows/wsl.

**Comment by WadeBarnes** [comment]
@jamshale, This sounds like a different issue than the one reported here.  If so, please open a separate issue and we can discuss there.
