### ISSUE TITLE
Issues restarting existing von-network instance

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-network#60]
[PR 59](https://github.com/bcgov/von-network/pull/59) fixed some issues with restarting an existing instance, however the following issue now occurs.

The containers start, but the web server encounters the following exception and the Ledger Browser hangs at the Connecting to server screen.

![image](https://user-images.githubusercontent.com/10504350/60200555-30091d80-97fb-11e9-9b08-68991c6d180c.png)

```
webserver_1  | WARNING:indy.libindy:_indy_loop_callback: Function returned error (<ErrorCode.DidAlreadyExistsError: 600>, {'message': 'Error: DID already exists\n  Caused by: V4SGRU86Z58d6TV7PBUe6f\n', 'backtrace': ''})
webserver_1  | ERROR:server.anchor:(<ErrorCode.DidAlreadyExistsError: 600>, {'message': 'Error: DID already exists\n  Caused by: V4SGRU86Z58d6TV7PBUe6f\n', 'backtrace': ''})
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/home/indy/server/anchor.py", line 213, in _open_wallet
webserver_1  |     {'seed': LEDGER_SEED}
webserver_1  |   File "/home/indy/.pyenv/versions/3.5.6/lib/python3.5/site-packages/indy/did.py", line 51, in create_and_store_my_did
webserver_1  |     create_and_store_my_did.cb)
webserver_1  |   File "/home/indy/.pyenv/versions/3.5.6/lib/python3.5/asyncio/futures.py", line 381, in __iter__
webserver_1  |     yield self  # This tells Task to wait for completion.
webserver_1  |   File "/home/indy/.pyenv/versions/3.5.6/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
webserver_1  |     future.result()
webserver_1  |   File "/home/indy/.pyenv/versions/3.5.6/lib/python3.5/asyncio/futures.py", line 294, in result
webserver_1  |     raise self._exception
webserver_1  | indy.error.IndyError: (<ErrorCode.DidAlreadyExistsError: 600>, {'message': 'Error: DID already exists\n  Caused by: V4SGRU86Z58d6TV7PBUe6f\n', 'backtrace': ''})
webserver_1  |
webserver_1  | During handling of the above exception, another exception occurred:
webserver_1  |
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/home/indy/server/anchor.py", line 226, in open
webserver_1  |     await self._open_wallet()
webserver_1  |   File "/home/indy/server/anchor.py", line 216, in _open_wallet
webserver_1  |     raise AnchorException(str(e))
webserver_1  | server.anchor.AnchorException: (<ErrorCode.DidAlreadyExistsError: 600>, {'message': 'Error: DID already exists\n  Caused by: V4SGRU86Z58d6TV7PBUe6f\n', 'backtrace': ''})
webserver_1  | INFO:__main__:--- Trust anchor initialized ---
```

### Steps to reproduce:
`./manage down` to clean up existing containers and volumes
`./manage build` to build the latest version of `master`
`./manage up`
The containers will start and the Ledger Browser will connect this first time.
`./manage stop` to stop the containers without deleting the volumes.
`./manage up`
The containers will start, the web server will eventually encounter the exception above, and the Ledger Browser will hang at the Connecting to server screen.

**Comment by WadeBarnes** [comment]
[PR 61](https://github.com/bcgov/von-network/pull/61) addresses the issue reports above and allows the `von-network` instance to be restarted.  However the restarted instance does not function correctly.

The Validator Node status does not update.  The node containers indicate they are not collecting status information. 
![image](https://user-images.githubusercontent.com/10504350/60209015-9a778900-980e-11e9-90a7-f3d700a5c833.png)

The restated instance will also not allow you to register new DIDs (at least via a seed), unlike the first time you start it where is allows you to register new DIDs.

**Comment by WadeBarnes** [comment]
Latest updates to [PR 61](https://github.com/bcgov/von-network/pull/61) resolve the issues.
